package com.github.paganini2008.devtools.db4j;

import java.util.Map;

/**
 * KeyHolder
 * 
 * @author Jimmy Hoff
 * @version 1.0
 */
public interface GeneratedKey {

	String[] getKeyNames();
	
	Map<String, Object> getKeys();

	Number getKey();

	Object getKey(String keyName);

	void setKeys(Map<String, Object> map);
	
	static GeneratedKey autoGenerated() {
		return forNames(new String[0]);
	}

	static GeneratedKey forNames(String[] columnNames) {
		return new GeneratedKeyImpl(columnNames);
	}

}
